In [1]:
import numpy as np
from single import GameManager

In [2]:
g = GameManager()
g.pprint()

[40  7  7  5  5  5  0  0  0  0  0  0  0  0  0  0  0  6  6  5  5  5  0  0
  0  0  0  0  0  0  0  0  0  5  5  5  5  5  0  0  0  0  0  0  0  0  0  0
  0  5  3  3  2  2  1  1  0  0  0  0  0  0  0  0  0  5  3  3  2  2  1  1
  0  0  0  0  0  0  0  0  0  4  3  2  1  1  1  1  1  1  0  0  0  0  0  0
  0  8  8  9  9 10  9 10 10  8  0  4  4  5  6  4  6  6  5  5  0  2  2  1
  1  2  3  3  1  3  0  0  1  0  1  0  0  3  1  0  2  0  1  0  1  0  0  0
  4  1  0  0]


array([1, 0, 2, 0, 1, 0, 1, 0, 0, 0])

In [3]:
g.get_camels()
g.pprint()

[37  7  7  5  5  5  0  0  0  0  0  0  0  0  0  0  0  6  6  5  5  5  0  0
  0  0  0  0  0  0  0  0  0  5  5  5  5  5  0  0  0  0  0  0  0  0  0  0
  0  5  3  3  2  2  1  1  0  0  0  0  0  0  0  0  0  5  3  3  2  2  1  1
  0  0  0  0  0  0  0  0  0  4  3  2  1  1  1  1  1  1  0  0  0  0  0  0
  0  8  8  9  9 10  9 10 10  8  0  4  4  5  6  4  6  6  5  5  0  2  2  1
  1  2  3  3  1  3  0  0  1  0  1  1  2  0  1  0  2  0  1  0  4  0  0  0
  4  1  0  0]


array([1, 0, 2, 0, 1, 0, 4, 0, 0, 0])

In [4]:
g.sell(np.array([0, 0, 2, 0, 0, 0, 0]))
g.pprint()

[37  7  7  5  5  5  0  0  0  0  0  0  0  0  0  0  0  6  6  5  5  5  0  0
  0  0  0  0  0  0  0  0  0  5  5  5  0  0  0  0  0  0  0  0  0  0  0  0
  0  5  3  3  2  2  1  1  0  0  0  0  0  0  0  0  0  5  3  3  2  2  1  1
  0  0  0  0  0  0  0  0  0  4  3  2  1  1  1  1  1  1  0  0  0  0  0  0
  0  8  8  9  9 10  9 10 10  8  0  4  4  5  6  4  6  6  5  5  0  2  2  1
  1  2  3  3  1  3  0  0  1  0  1  1  2  0  1  0  0  0  1  0  4 10  0  0
  4  1  0  0]


array([ 1,  0,  0,  0,  1,  0,  4, 10,  0,  0])

In [5]:
g.exchange(np.array([0, 1, 0, 1, 0, 0, -2]))
g.pprint()

[37  7  7  5  5  5  0  0  0  0  0  0  0  0  0  0  0  6  6  5  5  5  0  0
  0  0  0  0  0  0  0  0  0  5  5  5  0  0  0  0  0  0  0  0  0  0  0  0
  0  5  3  3  2  2  1  1  0  0  0  0  0  0  0  0  0  5  3  3  2  2  1  1
  0  0  0  0  0  0  0  0  0  4  3  2  1  1  1  1  1  1  0  0  0  0  0  0
  0  8  8  9  9 10  9 10 10  8  0  4  4  5  6  4  6  6  5  5  0  2  2  1
  1  2  3  3  1  3  0  0  0  0  0  1  2  2  1  1  0  1  1  0  2 10  0  0
  4  1  0  0]


array([ 1,  1,  0,  1,  1,  0,  2, 10,  0,  0])

In [6]:
g.get(np.array([0, 0, 0, 0, 1, 0, 0]))
g.pprint()

[36  7  7  5  5  5  0  0  0  0  0  0  0  0  0  0  0  6  6  5  5  5  0  0
  0  0  0  0  0  0  0  0  0  5  5  5  0  0  0  0  0  0  0  0  0  0  0  0
  0  5  3  3  2  2  1  1  0  0  0  0  0  0  0  0  0  5  3  3  2  2  1  1
  0  0  0  0  0  0  0  0  0  4  3  2  1  1  1  1  1  1  0  0  0  0  0  0
  0  8  8  9  9 10  9 10 10  8  0  4  4  5  6  4  6  6  5  5  0  2  2  1
  1  2  3  3  1  3  0  0  0  0  0  1  3  2  1  1  0  1  2  0  2 10  0  0
  4  1  0  0]


array([ 1,  1,  0,  1,  2,  0,  2, 10,  0,  0])